
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jiyop
 */
public class ServerSelection extends javax.swing.JFrame {
    FileServer server;
    /**
     * Creates new form ServerSelection
     */
  public ServerSelection() {
    initComponents();
    jLabel1.setForeground(new Color(33, 33, 33));
    BufferedImage img = new BufferedImage(32, 32, BufferedImage.TYPE_INT_ARGB);
Graphics2D g = img.createGraphics();

g.setColor(new Color(41, 121, 255));
g.fillRoundRect(0, 0, 32, 32, 8, 8);

g.setColor(Color.WHITE);
g.setFont(new Font("Segoe UI", Font.BOLD, 30));
g.drawString("F", 8, 24);

g.dispose();

setIconImage(img);
    setLocationRelativeTo(null);
setSize(400, 400);
getContentPane().setBackground(new Color(245, 247, 250));
btnRunServer.setFont(new java.awt.Font("Segoe UI", 1, 16));
btnRunServer.setText("Run As Server");
 btnRunServer.setFocusPainted(false);
    btnRunServer.setBorderPainted(false);
    btnRunServer.setContentAreaFilled(true);
    btnRunServer.setBackground(new Color(41,121,255)); // modern blue
    btnRunServer.setForeground(Color.WHITE);

    styleButton(btnLocalhost);
    styleButton(btnCustomIP);
     
}
 private void styleButton(javax.swing.JButton button) {

    button.setFocusPainted(false);
    button.setBorderPainted(false);
    button.setContentAreaFilled(true);
    button.setBackground(new Color(41,121,255)); // modern blue
    button.setForeground(Color.WHITE);
    button.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        button.setBackground(new Color(30,100,220));
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        button.setBackground(new Color(41,121,255));
    }
});
    button.setFont(new Font("Segoe UI", Font.BOLD, 16));
    button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    button.setPreferredSize(new java.awt.Dimension(220, 45));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLocalhost = new javax.swing.JButton();
        btnCustomIP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRunServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnLocalhost.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLocalhost.setText("use localhost");
        btnLocalhost.setToolTipText("");
        btnLocalhost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalhostActionPerformed(evt);
            }
        });

        btnCustomIP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCustomIP.setText("Custom IP");
        btnCustomIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomIPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select your server");

        btnRunServer.setText("run as server");
        btnRunServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 81, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLocalhost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRunServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(btnLocalhost)
                .addGap(18, 18, 18)
                .addComponent(btnCustomIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnRunServer)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomIPActionPerformed
      javax.swing.JTextField txtIP = new javax.swing.JTextField();

    Object[] message = {
        "Enter Server IP:",
        txtIP
    };

    int option = javax.swing.JOptionPane.showConfirmDialog(
            this,
            message,
            "Custom Server",
            javax.swing.JOptionPane.OK_CANCEL_OPTION
    );

    if (option == javax.swing.JOptionPane.OK_OPTION) {

        String serverIP = txtIP.getText();

        if (serverIP.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "IP cannot be empty");
            return;
        }

        new LoginRegister(serverIP).setVisible(true);
        dispose();
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomIPActionPerformed

    private void btnLocalhostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalhostActionPerformed
 new LoginRegister("127.0.0.1").setVisible(true);
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocalhostActionPerformed

    private void btnRunServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunServerActionPerformed
        try {

        try {
    String jarDir = new File(
        FileServer.class
            .getProtectionDomain()
            .getCodeSource()
            .getLocation()
            .toURI()
    ).getParent();

    String serverFolder = jarDir + File.separator + "FileBottleServer";

    System.out.println("SERVER ROOT: " + serverFolder);

     server = new FileServer(serverFolder);
new Thread(server).start();
} catch (Exception e) {
    e.printStackTrace();
}

        JFrame serverFrame = new JFrame("FileBottle Server");
serverFrame.setSize(450, 300);
serverFrame.setLocationRelativeTo(null);
serverFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
serverFrame.getContentPane().setBackground(new Color(18, 22, 30));
serverFrame.setLayout(new BorderLayout());
BufferedImage img = new BufferedImage(32, 32, BufferedImage.TYPE_INT_ARGB);
Graphics2D g = img.createGraphics();

g.setColor(new Color(41, 121, 255));
g.fillRoundRect(0, 0, 32, 32, 8, 8);

g.setColor(Color.WHITE);
g.setFont(new Font("Segoe UI", Font.BOLD, 30));
g.drawString("F", 8, 24);

g.dispose();

serverFrame.setIconImage(img);
JPanel mainPanel = new JPanel();
mainPanel.setBackground(new Color(18, 22, 30));
mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
mainPanel.setBorder(BorderFactory.createEmptyBorder(30, 30, 30, 30));

JLabel title = new JLabel("SERVER RUNNING");
title.setFont(new Font("Segoe UI", Font.BOLD, 22));
title.setForeground(new Color(41,121,255));
title.setAlignmentX(Component.CENTER_ALIGNMENT);

String ip = java.net.InetAddress.getLocalHost().getHostAddress();

JLabel ipLabel = new JLabel("IP: " + ip);
ipLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
ipLabel.setForeground(new Color(0, 200, 150));
ipLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

// Connected Clients Label
JLabel clientsLabel = new JLabel("Connected Clients: 0");
clientsLabel.setFont(new Font("Segoe UI", Font.PLAIN, 16));
clientsLabel.setForeground(Color.WHITE);
clientsLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

// Stop Button
JButton stopBtn = new JButton("Stop Server");
stopBtn.setFocusPainted(false);
stopBtn.setBackground(new Color(220, 53, 69));
stopBtn.setForeground(Color.WHITE);
stopBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
stopBtn.setAlignmentX(Component.CENTER_ALIGNMENT);

stopBtn.addActionListener(e -> {
    server.stopServer();
    JOptionPane.showMessageDialog(serverFrame, "Server Stopped.");
    System.exit(0);
});

mainPanel.add(title);
mainPanel.add(Box.createVerticalStrut(15));
mainPanel.add(ipLabel);
mainPanel.add(Box.createVerticalStrut(20));
mainPanel.add(clientsLabel);
mainPanel.add(Box.createVerticalStrut(25));
mainPanel.add(stopBtn);

serverFrame.add(mainPanel, BorderLayout.CENTER);
serverFrame.setVisible(true);
dispose();

new javax.swing.Timer(1000, e -> {
    clientsLabel.setText(
        "Connected Clients: " + FileServer.getConnectedClients()
    );
}).start();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Server failed: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRunServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomIP;
    private javax.swing.JButton btnLocalhost;
    private javax.swing.JButton btnRunServer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
