
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jiyop
 */
public class SplashScreen extends javax.swing.JFrame {
    
private void fadeIn() {

    setOpacity(0f);   // start fully transparent

    Timer fadeTimer = new Timer(20, null);

    fadeTimer.addActionListener(new java.awt.event.ActionListener() {

        float opacity = 0f;

        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {

            opacity += 0.05f;   // increase speed here

            if (opacity >= 1f) {
                opacity = 1f;
                fadeTimer.stop();
            }

            setOpacity(opacity);
        }
    });

    fadeTimer.start();
}
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {

    setUndecorated(true);

    setSize(500, 560);   // 500 for image + space for progress bar
    setLocationRelativeTo(null);

   getContentPane().setBackground(new Color(245,245,245));
    getContentPane().setLayout(new BorderLayout());

    // Load logo
    ImageIcon icon = new ImageIcon(
            getClass().getResource("logo.png")
    );

    JLabel logoLabel = new JLabel(icon);
    logoLabel.setHorizontalAlignment(SwingConstants.CENTER);
logoLabel.setBorder(
    BorderFactory.createEmptyBorder(10, 10, 10, 10)
);
    // Progress Bar
    progressBar = new JProgressBar();
    progressBar.setStringPainted(true);
    progressBar.setBorderPainted(false);
    progressBar.setPreferredSize(new Dimension(500, 25));
    progressBar.setForeground(new Color(70,130,180));

    add(logoLabel, BorderLayout.CENTER);
    add(progressBar, BorderLayout.SOUTH);
fadeIn();
    startLoading();
}
private void startLoading() {

    javax.swing.Timer timer = new javax.swing.Timer(30, null);

    timer.addActionListener(new java.awt.event.ActionListener() {

        int value = 0;

        public void actionPerformed(java.awt.event.ActionEvent evt) {

            value++;
            progressBar.setValue(value);

            if (value >= 100) {
                timer.stop();

new ServerSelection().setVisible(true);

                dispose();
            }
        }
    });

    timer.start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(400,400);

        progressBar.setBorderPainted(false);
        progressBar.setStringPainted(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1)))
                .addGap(587, 587, 587))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(794, 794, 794)
                .addComponent(jLabel1)
                .addGap(111, 111, 111)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
